routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\ContactsController;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\LocalizationController;
use App\Http\Controllers\PersonalController;
use App\Http\Controllers\SettingsController;
use Illuminate\Support\Facades\Route;

Route::controller(AuthController::class)->group(function () {
    Route::get('/', 'index')->name('login');
    Route::post('login', 'postLogin')->name('login.post');

    Route::get('lang/{locale}', [LocalizationController::class, 'index']);

    Route::middleware('auth')->group(function () {
        Route::post('logout', 'logout')->name('logout');

        Route::resource('contacts', ContactsController::class);
        Route::resource('departments', DepartmentController::class);
        Route::resource('settings', SettingsController::class);
        Route::post('settings/add-position', [SettingsController::class, 'addPosition'])->name('add-position');

        Route::post('personal/download/{id}', [PersonalController::class, 'download']);
        Route::get('personal/work-time', [PersonalController::class, 'workTime'])->name('work-time');
        Route::post('personal/add-time', [PersonalController::class, 'addTime'])->name('add-time');
        Route::resource('personal', PersonalController::class);

        Route::get('country-list', [ContactsController::class, 'countryList']);
        Route::get('positions-list', [ContactsController::class, 'positionsList']);
        Route::get('departments-list', [ContactsController::class, 'departmentsList']);
    });
});

resources/views/sections/contacts.blade.php
@extends('layouts.main')

@section('css-scripts')
    <link href="{{ asset('css/contacts.css') }}" rel="stylesheet" />
@endsection

@section('content')
    <div style="margin-bottom: 10px;" class="container">
        <span class="tab-name">Kontaktai</span>

        <div class="inlineButton">
            <a class="btn button toggle-button" id="openFilter"><i class="fa-solid fa-filter"></i></a>
        </div>

        <div id="remove-button" class="inlineButton" style="display: none">
            <a class="btn button toggle-button" id="removeContact" style="background: #c13a3a;">
                <i class="fa-solid fa-xmark" style="color: white"></i>
            </a>
        </div>

        <div id="sLetters">
            <div class='clear-selection letter'><i class="fa-solid fa-xmark"></i></div>
            <div class="nLetter">#</div>
        </div>

        <div style="display: none; margin-top: 20px;" id="filterForm">
            <div class="row">
                <div class="col-4">
                    <label for="filterContinent" class="form-label">Žemynas</label>
                    <select id="filterContinent" class='selectpicker' data-live-search="true">
                        <option value="0">Visi</option>
                        @foreach($continents as $continent)
                            <option value="{{$continent->id}}">{{$continent->name}}</option>
                        @endforeach
                    </select>
                </div>
                <div class="col-4">
                    <label for="filterCountry" class="form-label">Šalis</label>
                    <select id="filterCountry" class='selectpicker' data-live-search="true">
                        <option value="0">Visos</option>
                        @foreach($countries as $country)
                            <option value="{{$country->id}}">{{$country->name}}</option>
                        @endforeach
                    </select>
                </div>
                <div class="col-4">
                    <label for="filterPosition" class="form-label">Pareigos</label>
                    <select id="filterPosition" class='selectpicker' data-live-search="true">
                        <option value="0">Visos</option>
                        @foreach($positions as $position)
                            <option value="{{$position->id}}">{{$position->name}}</option>
                        @endforeach
                    </select>
                </div>
            </div>
        </div>
    </div>

    <div id="restriction"></div>

    <div class="container" style="margin-top: 4%">
        <table class="table row-border table-hover" id="datatable-Contact" style="width:100%">
            <thead>
                <tr>
                    <th style="width: 20px"><label class="checkboxColor"><input type="checkbox" id="selectAll"/></label></th>
                    <th style="width: 10px"></th>
                    <th>Vardas</th>
                    <th>Pavardė</th>
                    <th>El. paštas</th>
                    <th>Valstybė</th>
                    <th>Pareigos</th>
                    <th>Skyrius</th>
                    <th>Telefonas</th>
                    <th>Įmonėje nuo</th>
                    <th style="width: 20px"></th>
                </tr>
            </thead><tbody></tbody>
        </table>
    </div>
@endsection

@section('js-scripts')
    <script type="text/javascript" src="{{ asset('js/contacts.js') }}"></script>
@endsection

resources/views/sections/departments.blade.php
@extends('layouts.main')

@section('css-scripts')
    <link href="{{ asset('css/departments.css') }}" rel="stylesheet" />
@endsection

@section('content')
    <div style="margin-bottom: 10px;" class="container">
        <span class="tab-name">{{ __('cruds.department.title') }}</span>
        <div id="download-button" class="inlineButton">
            <a class="btn btn-success toggle-button" id="download"><i class="fa-solid fa-arrow-down"></i></a>
        </div>

        <div class="inlineButton" data-bs-toggle="modal" data-bs-target="#addNewModal">
            <a class="btn button toggle-button" id="addRow"><i class="fa-solid fa-plus"></i></a>
        </div>

        <div class="inlineButton">
            <a class="btn button toggle-button" id="openFilter"><i class="fa-solid fa-filter"></i></a>
        </div>

        <div id="remove-button" class="inlineButton" style="display: none">
            <a class="btn button toggle-button" id="removeDepartment" style="background: #c13a3a;">
                <i class="fa-solid fa-xmark" style="color: white"></i>
            </a>
        </div>

        <div class="modal fade" id="addNewModal" tabindex="-1" aria-labelledby="addDepartment" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content" style="border-radius: 15px; width: 100%">
                    <div class="modal-header">
                        <h5 class="modal-title" id="addDepartment">Skyriaus pridėjimas</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <form id="addDepartmentForm" action="{{ route("departments.store") }}">
                            @csrf
                            <div class="row g-3 departmentFields align-items-center">
                                <div class="col-12">
                                    <input type="text" class="form-control" name="name" aria-label="Pavadinimas" placeholder="Pavadinimas">
                                </div>
                                <div class="col-md-6">
                                    <input type="email" class="form-control" name="email" aria-label="ePastas" placeholder="El. paštas">
                                </div>
                                <div class="col-auto">
                                    <label for="country" class="col-form-label">Šalis:</label>
                                </div>
                                <div class="col">
                                    <select id="countryPick" class="selectpicker" aria-label="Valstybė" data-live-search="true">
                                    @foreach($countries as $country)
                                        <option value="{{$country->id}}">{{$country->name}}</option>
                                    @endforeach
                                    </select>
                                </div>
                                <div class="col-12">
                                    <input type="tel" class="form-control" name="phone" aria-label="Telefonas" placeholder="Telefonas">
                                </div>
                                <div class="addComment">
                                    <button id="newComment" type="button" class="new-button">
                                        <i class="fa fa-plus" style="color: #45484b; margin-top: 6px"></i>
                                    </button>
                                    <span>Pridėti komentarą</span>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button id="submitDepartment" form='addDepartmentForm' type="submit" class="btn btn-primary">Išsaugoti</button>
                    </div>
                </div>
            </div>
        </div>

        <div id="sLetters">
            <div class='clear-selection letter'><i class="fa-solid fa-xmark"></i></div>
            <div class="nLetter">#</div>
        </div>

        <div style="display: none; margin-top: 20px;" id="filterForm">
            <div class="row">
                <div class="col-4">
                    <label for="filterContinent" class="form-label">Žemynas</label>
                    <select id="filterContinent" class='selectpicker' data-live-search="true">
                        <option value="0">Visi</option>
                        @foreach($continents as $continent)
                            <option value="{{$continent->id}}">{{$continent->name}}</option>
                        @endforeach
                    </select>
                </div>
                <div class="col-4">
                    <label for="filterCountry" class="form-label">Šalis</label>
                    <select id="filterCountry" class='selectpicker' data-live-search="true">
                        <option value="0">Visos</option>
                        @foreach($countries as $country)
                            <option value="{{$country->id}}">{{$country->name}}</option>
                        @endforeach
                    </select>
                </div>
                <div class="col-4">
                    <div class="form-check" style="margin-top: 9px;">
                        <input class="form-check-input" type="checkbox" id="mailSent">
                        <label class="form-check-label" for="mailSent">Išsiųstas laiškas</label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" id="withComment">
                        <label class="form-check-label" for="withComment">Su komentaru</label>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="restriction"></div>

    <div class="container" style="margin-top: 4%">
        <table class="table row-border table-hover" id="datatable-Department" style="width:100%">
            <thead>
                <tr>
                    <th style="width: 20px"><label class="checkboxColor"><input type="checkbox" id="selectAll"/></label></th>
                    <th>{{ __('cruds.department.fields.name') }}</th>
                    <th>{{ __('cruds.department.fields.email') }}</th>
                    <th>{{ __('cruds.department.fields.country') }}</th>
                    <th>{{ __('cruds.department.fields.phone') }}</th>
                    <th>{{ __('cruds.department.fields.comment') }}</th>
                    <th style="width: 20px"></th>
                </tr>
            </thead><tbody></tbody>
        </table>
    </div>
@endsection

@section('js-scripts')
    <script type="text/javascript" src="{{ asset('js/departments.js') }}"></script>
@endsection

resources/views/sections/personal.blade.php
@extends('layouts.main')

@section('css-scripts')
    <link href="https://cdn.jsdelivr.net/npm/@eonasdan/tempus-dominus@6.0.0-beta4/dist/css/tempus-dominus.min.css" rel="stylesheet" crossorigin="anonymous">
    <link href="{{ asset('css/personal.css') }}" rel="stylesheet"/>
@endsection

@section('content')
    <div style="margin-bottom: 20px; padding: 0" class="container">
        <span class="tab-name">{{ __('cruds.personal.title') }}</span>

        <div id="remove-button" class="inlineButton" style="display: none">
            <a class="btn button toggle-button" id="removeFile" style="background: #c13a3a;">
                <i class="fa-solid fa-xmark" style="color: white"></i>
            </a>
        </div>
    </div>

    <div class="container files" style="padding: 0; float: left; width: 60%;">
        <div id="add-file">
            <a class="btn button toggle-button" id="addFile"><i class="fa-solid fa-plus"></i></a>
            <span style="letter-spacing: 0.5px;">Pridėti failą</span>
        </div>

        <div style="display: none; width: 90%" id="fileToggle">
            <form id="addFileForm" action="{{ route("personal.store") }}">
                @csrf
                <div class="row" style="margin-top: 15px;">
                    <div class="col-7">
                        <input class="form-control" type="text" placeholder="Pavadinimas" aria-label="Pavadinimas"
                               name="title">
                    </div>
                    <div class="col-5">
                        <input class="form-control form-control" id="formFile" type="file" name="file">
                    </div>
                    <div class="mb-3" style="margin-top: 15px;">
                        <textarea class="form-control" aria-label="Aprašymas" name="details"></textarea>
                    </div>
                    <div class="col-12" style="display: flex; align-items: center">
                        <button id="submitFile" type="submit" class="btn btn-success round">Įkelti</button>
                        <span class="error-message"></span>
                    </div>
                </div>
            </form>
        </div>

        <table class="col table row-border table-hover" id="datatable-PersonalFiles" style=" margin: 0">
            <thead>
            <tr>
                <th style="width: 20px"><label class="checkboxColor"><input type="checkbox" id="selectAll"/></label>
                </th>
                <th>{{ __('cruds.personal.fields.name') }}</th>
                <th>{{ __('cruds.personal.fields.details') }}</th>
                <th>{{ __('cruds.personal.fields.created_at') }}</th>
                <th style="width: 20px"></th>
                <th style="width: 20px"></th>
            </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>

    <div class="container" style="padding: 0; float: right; width: 35%;">
        <form id="addWorkTimeForm" action="{{ route("work-time") }}">
            @csrf
            <div class="row">
                <div class="col-2">
                    <a class="btn button toggle-button" id="addTime"><i class="fa-solid fa-plus"></i></a>
                </div>
                <div class="col-5">
                    <input type="text" class="form-control datetimepicker-input" id="date-from" data-toggle="date-from" data-target="#date-from" name="date_from"/>
                </div>
                <div class="col-5">
                    <input type="text" class="form-control datetimepicker-input" id="date-till" data-toggle="date-till" data-target="#date-till" name="date_till"/>
                </div>
            </div>
        </form>

        <table class="col table row-border table-hover" id="datatable-WorkTime" style=" margin: 0">
            <thead>
            <tr>
                <th>Diena</th>
                <th>{{ __('cruds.personal.fields.time_from') }}</th>
                <th>{{ __('cruds.personal.fields.time_till') }}</th>
            </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
@endsection

@section('js-scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.11.5/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@eonasdan/tempus-dominus@6.0.0-beta4/dist/js/tempus-dominus.min.js" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{{ asset('js/personal.js') }}"></script>
@endsection

resources/views/sections/settings.blade.php
@extends('layouts.main')

@section('css-scripts')
    <link href="{{ asset('css/settings.css') }}" rel="stylesheet"/>
@endsection

@section('content')
    <div style="margin-bottom: 10px;" class="container">
        <span class="tab-name">{{ __('cruds.settings.title') }}</span>
    </div>

    <div class="container">
        <div class="buttons-side" style="width: 30%; float: left">
            <div id="edit-personal">
                <a class="btn button toggle-button" id="edit-personal"><i class="fa-solid fa-plus"></i></a>
                <span>Redaguoti asmeninius duomenis</span>
            </div>

            <div id="add-employee" style="margin-top: 10px;">
                <a class="btn button toggle-button" id="addRow"><i class="fa-solid fa-plus"></i></a>
                <span>Pridėti darbuotoją</span>
            </div>

            <div id="add-position" style="margin-top: 10px;">
                <a class="btn button toggle-button" id="add-position"><i class="fa-solid fa-plus"></i></a>
                <span>Pridėti pareigas</span>
            </div>
        </div>

        <div class="toggle-side" style="width: 70%; float: right">
            <div id="personal-card" class="card employee-card">
                <div class="card-body">
                    <form id="editPersonalForm" class="row g-3" data-id="{{ $personal->id }}">
                        @csrf
                        <div class="col-md-6">
                            <label for="inputName" class="form-label">Vardas</label>
                            <input type="text" class="form-control" id="inputName" name="name"
                                   value="{{ $personal->name }}">
                        </div>
                        <div class="col-md-6">
                            <label for="inputSurname" class="form-label">Pavardė</label>
                            <input type="text" class="form-control" id="inputSurname" name="surname"
                                   value="{{ $personal->surname }}">
                        </div>
                        <div class="col-md-6">
                            <label for="inputEmail" class="form-label">El. paštas</label>
                            <input type="email" class="form-control" id="inputEmail" name="email"
                                   value="{{ $personal->email }}">
                        </div>
                        <div class="col-md-6">
                            <label for="inputPhone" class="form-label">Telefonas</label>
                            <input type="tel" class="form-control" id="inputPhone" name="phone"
                                   value="{{ $personal->phone }}">
                        </div>
                        <div class="col-6">
                            <label for="inputAddress1" class="form-label">Adresas (1)</label>
                            <input type="text" class="form-control" id="inputAddress1"
                                   name="address_1" value="{{ $personal->address->address_1 }}">
                        </div>
                        <div class="col-6">
                            <label for="inputAddress2" class="form-label">Adresas (2)</label>
                            <input type="text" class="form-control" id="inputAddress2" name="address_2"
                                   value="{{ $personal->address->address_2 }}">
                        </div>
                        <div class="col-md-6">
                            <label for="inputCity" class="form-label">Miestas</label>
                            <input type="text" class="form-control" id="inputCity" name="city"
                                   value="{{ $personal->address->city }}">
                        </div>
                        <div class="col-md-6">
                            <label for="inputZip" class="form-label">Pašto kodas</label>
                            <input type="text" class="form-control" id="inputZip" name="zip_code"
                                   value="{{ $personal->address->zip_code }}">
                        </div>
                        <div class="col-12">
                            <button id="submitEditPersonal" type="submit" class="btn btn-success round">Keisti</button>
                        </div>
                    </form>
                </div>
            </div>

            <div style="display: none; width: 90%" class="position-card">
                <form id="addPositionForm">
                    @csrf
                    <div class="row" style="margin-top: 15px;">
                        <div class="col-6">
                            <input class="form-control" type="text" placeholder="Pavadinimas" aria-label="Pavadinimas"
                                   name="name">
                        </div>
                        <div class="col-12" style="display: flex; align-items: center; margin-top: 10px;">
                            <button id="submitPosition" type="submit" class="btn btn-success round">Pridėti</button>
                            <span class="error-message"></span>
                        </div>
                    </div>
                </form>
            </div>

            <div id="employee-card" class="card employee-card">
                <div class="card-body">
                    <form id="newEmployeeForm" class="row g-3">
                        @csrf
                        <div class="col-md-6">
                            <label for="inputName" class="form-label">Vardas</label>
                            <input type="text" class="form-control" id="inputName" name="name">
                        </div>
                        <div class="col-md-6">
                            <label for="inputSurname" class="form-label">Pavardė</label>
                            <input type="text" class="form-control" id="inputSurname" name="surname">
                        </div>
                        <div class="col-md-6">
                            <label for="inputDepartment" class="form-label">Skyrius</label>
                            <select id="inputDepartment" class="form-select">
                                @foreach($departments as $department)
                                    <option value="{{$department->id}}">{{$department->name}}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="col-md-6">
                            <label for="inputPosition" class="form-label">Pareigos</label>
                            <select id="inputPosition" class="form-select">
                                @foreach($positions as $position)
                                    <option value="{{$position->id}}">{{$position->name}}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="col-md-6">
                            <label for="inputEmail" class="form-label">El. paštas</label>
                            <input type="email" class="form-control" id="inputEmail" name="email">
                        </div>
                        <div class="col-md-6">
                            <label for="inputPhone" class="form-label">Telefonas</label>
                            <input type="tel" class="form-control" id="inputPhone" name="phone">
                        </div>
                        <div class="col-6">
                            <label for="inputAddress1" class="form-label">Adresas (1)</label>
                            <input type="text" class="form-control" id="inputAddress1" placeholder="Gedimino pr. 99"
                                   name="address_1">
                        </div>
                        <div class="col-6">
                            <label for="inputAddress2" class="form-label">Adresas (2)</label>
                            <input type="text" class="form-control" id="inputAddress2" name="address_2">
                        </div>
                        <div class="col-md-4">
                            <label for="inputCountry" class="form-label">Tautybė</label>
                            <select id="inputCountry" class="form-select">
                                @foreach($countries as $country)
                                    <option value="{{$country->id}}">{{$country->name}}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="col-md-4">
                            <label for="inputCity" class="form-label">Miestas</label>
                            <input type="text" class="form-control" id="inputCity" name="city">
                        </div>
                        <div class="col-md-4">
                            <label for="inputZip" class="form-label">Pašto kodas</label>
                            <input type="text" class="form-control" id="inputZip" name="zip_code">
                        </div>
                        <div class="col-md-6">
                            <label for="inputPassword" class="form-label">Laikinas slaptažodis</label>
                            <input type="password" class="form-control" id="inputPassword" name="password"
                                   onkeyUp="document.getElementById('printPasswordBox').innerHTML = this.value">
                        </div>
                        <div class="col-md-6">
                            <label for="inputPassword" class="form-label">Pakartokite slaptažodį</label>
                            <input type="password" class="form-control" id="repeatPassword"
                                   name="password_confirmation">
                        </div>
                        <div id='printPasswordBox' class='passwordTyping'></div>
                        <div class="col-12">
                            <button id="submitEmployee" type="submit" class="btn btn-primary">Pridėti</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

@endsection

@section('js-scripts')
    <script type="text/javascript" src="{{ asset('js/settings.js') }}"></script>
@endsection